# Generated by Django 3.2.16 on 2024-10-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_auto_20230924_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=25, verbose_name='Тег'),
        ),
    ]
